
version: '3'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: mysql
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: sample
    ports:
        - "3306:3306"

  postgres:
    image: postgres:10.7-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: sample
    ports:
        - "5001:5432"